import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Login</Link>
        </li>
        <li>
          <Link to="/schedulereschedule">ScheduleReschedule</Link>
        </li>
        <li>
          <Link to="/profilescreen">ProfileScreen</Link>
        </li>
        <li>
          <Link to="/documents">Documents</Link>
        </li>
        <li>
          <Link to="/medicalrecords">MedicalRecords</Link>
        </li>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
        <li>
          <Link to="/messagescreen">MessageScreen</Link>
        </li>
        <li>
          <Link to="/appointmentpopup">AppointmentPopup</Link>
        </li>
        <li>
          <Link to="/forms">Forms</Link>
        </li>
        <li>
          <Link to="/appointmenthistory">AppointmentHistory</Link>
        </li>
        <li>
          <Link to="/schedulingquestionnnaire">Schedulingquestionnnaire</Link>
        </li>
        <li>
          <Link to="/letters">Letters</Link>
        </li>
        <li>
          <Link to="/healthhistory">HealthHistory</Link>
        </li>
        <li>
          <Link to="/referrals">Referrals</Link>
        </li>
        <li>
          <Link to="/immunizations">Immunizations</Link>
        </li>
        <li>
          <Link to="/scheduleappointmentscreenone">
            ScheduleAppointmentScreenOne
          </Link>
        </li>
        <li>
          <Link to="/handouts">Handouts</Link>
        </li>
        <li>
          <Link to="/medicalclearances">MedicalClearances</Link>
        </li>
        <li>
          <Link to="/appointmentpopupone">AppointmentPopupOne</Link>
        </li>
        <li>
          <Link to="/insurancecard">InsuranceCard</Link>
        </li>
        <li>
          <Link to="/labresults">LabResults</Link>
        </li>
        <li>
          <Link to="/labresultsexpanded">LabResultsExpanded</Link>
        </li>
        <li>
          <Link to="/scheduleappointmentscreentwo">
            ScheduleAppointmentScreenTwo
          </Link>
        </li>
        <li>
          <Link to="/insurancecardexpanded">InsuranceCardExpanded</Link>
        </li>
        <li>
          <Link to="/scheduleappointmentscreenthree">
            ScheduleAppointmentScreenThree
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
